name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"  # Trigger on version tag pushes

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade build tools
        run: |
          pip install --upgrade pip setuptools wheel build twine

      - name: Build package
        run: python -m build

      - name: Publish package to Test PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload --repository-url https://upload.pypi.org/legacy/ dist/* --verbose

